name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out toolchain
      uses: actions/checkout@v2
      with:
        repository: miracoli/Saturn-SDK-GCC-SH2
        path: Saturn-SDK-GCC-SH2
    - name: Build toolchain
      # based on https://github.com/miracoli/Saturn-SDK-GCC-SH2/blob/master/.github/workflows/build.yml
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
              brew install coreutils
        fi
        echo SRCDIR $SRCDIR BUILDDIR $BUILDDIR TARGETMACH $TARGETMACH BUILDMACH $BUILDMACH HOSTMACH $HOSTMACH INSTALLDIR $INSTALLDIR SYSROOTDIR $SYSROOTDIR ROOTDIR $ROOTDIR DOWNLOADDIR $DOWNLOADDIR PROGRAM_PREFIX $PROGRAM_PREFIX
        sudo apt-get -y install automake autoconf-archive bison texinfo
        ./Saturn-SDK-GCC-SH2/build-elf.sh
        export PATH="$PATH:$(INSTALLDIR)/bin"
      env: 
        SRCDIR: ${{ github.workspace }}/source
        BUILDDIR:  ${{ github.workspace }}/build
        TARGETMACH: sh-elf
        BUILDMACH: x86_64-pc-linux-gnu
        HOSTMACH: x86_64-pc-linux-gnu
        INSTALLDIR:  ${{ github.workspace }}/toolchain
        SYSROOTDIR: ${{ github.workspace }}/toolchain/sysroot
        ROOTDIR:  ${{ github.workspace }}
        DOWNLOADDIR:  ${{ github.workspace }}/download
        PROGRAM_PREFIX: sh-none-elf-
        NCPU: 2
    - name: Check out satiator-menu
      uses: actions/checkout@v2
      with:
        path: satiator-menu
        submodules: true
    - name: Build satiator-menu
      run: |
        cd satiator-menu
        sudo apt-get -y install cmake
        make
    - name: Upload menu.bin artifact
      uses: actions/upload-artifact@v2
      with:
        name: menu.bin
        path: satiator-menu/menu.bin
